// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rw_rcpp
double rw_rcpp(int t);
RcppExport SEXP _rcpptst_rw_rcpp(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(rw_rcpp(t));
    return rcpp_result_gen;
END_RCPP
}
// rw_rcpp_arma
double rw_rcpp_arma(int t);
RcppExport SEXP _rcpptst_rw_rcpp_arma(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(rw_rcpp_arma(t));
    return rcpp_result_gen;
END_RCPP
}
// calc_ols
arma::mat calc_ols(arma::mat X, arma::vec y);
RcppExport SEXP _rcpptst_calc_ols(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(calc_ols(X, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcpptst_rw_rcpp", (DL_FUNC) &_rcpptst_rw_rcpp, 1},
    {"_rcpptst_rw_rcpp_arma", (DL_FUNC) &_rcpptst_rw_rcpp_arma, 1},
    {"_rcpptst_calc_ols", (DL_FUNC) &_rcpptst_calc_ols, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcpptst(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
