# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Passeggiata casuale con Rcpp
#' @description Simula il valore al tempo t di una passeggiata casuale
#' @param t numero di simulazioni
#' @return `int`
#' @export
rw_rcpp <- function(t) {
    .Call(`_rcpptst_rw_rcpp`, t)
}

#' Passeggiata casuale con RcppArmadillo
#' @description Simula il valore al tempo t di una passeggiata casuale
#' @param t numero di simulazioni
#' @return `int`
#' @export
rw_rcpp_arma <- function(t) {
    .Call(`_rcpptst_rw_rcpp_arma`, t)
}

.calc_ols <- function(X, y) {
    .Call(`_rcpptst_calc_ols`, X, y)
}

